import { createSlice, createEntityAdapter, createSelector, createAsyncThunk } from '@reduxjs/toolkit';

const API_BASE_URL = 'http://localhost:5000/api';

// Async thunk for fetching all employees
export const fetchEmployees = createAsyncThunk(
  'employees/fetchEmployees',
  async (_, { rejectWithValue }) => {
    try {
      const token = localStorage.getItem('authToken');
      const response = await fetch(`${API_BASE_URL}/employees`, {
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        }
      });
      if (!response.ok) throw new Error('Server error');
      return await response.json();
    } catch (error) {
      return rejectWithValue(error.message);
    }
  }
);

// Async thunk for adding an employee
export const addEmployee = createAsyncThunk(
  'employees/addEmployee',
  async (employeeData, { rejectWithValue }) => {
    try {
      const token = localStorage.getItem('authToken');
      const response = await fetch(`${API_BASE_URL}/employees`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(employeeData),
      });
      if (!response.ok) throw new Error('Could not add employee.');
      return await response.json();
    } catch (error) {
      return rejectWithValue(error.message);
    }
  }
);

// Async thunk for updating an employee
export const updateEmployee = createAsyncThunk(
  'employees/updateEmployee',
  async ({ id, changes }, { rejectWithValue }) => {
    try {
      const token = localStorage.getItem('authToken');
      const response = await fetch(`${API_BASE_URL}/employees/${id}`, {
        method: 'PATCH',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify(changes),
      });
      if (!response.ok) throw new Error('Could not update employee.');
      return await response.json();
    } catch (error) {
      return rejectWithValue(error.message);
    }
  }
);

// Async thunk for deleting an employee
export const deleteEmployee = createAsyncThunk(
  'employees/deleteEmployee',
  async (employeeId, { rejectWithValue }) => {
    try {
      const token = localStorage.getItem('authToken');
      const response = await fetch(`${API_BASE_URL}/employees/${employeeId}`, {
        method: 'DELETE',
        headers: {
          'Authorization': `Bearer ${token}`,
        }
      });
      // A successful DELETE might not return a body, so we check for a 204 (No Content) or 200 status
      if (!response.ok) {
        throw new Error('Could not delete employee.');
      }
      // On success, we return the ID so the reducer knows which employee to remove
      return employeeId;
    } catch (error) {
      return rejectWithValue(error.message);
    }
  }
);

// Create an entity adapter for employees.
// The `selectId` function tells the adapter that the unique ID for each employee is `employee.id`.
// The `sortComparer` function keeps the employee array sorted by first name, which can be useful for display.
const employeesAdapter = createEntityAdapter({
  selectId: (employee) => employee.id,
  sortComparer: (a, b) => a.firstName.localeCompare(b.firstName),
});

// Get the initial state from the adapter and populate it with seed data.
// The adapter creates an `{ ids: [], entities: {} }` structure.
const initialState = employeesAdapter.getInitialState({
  filters: {
    searchTerm: '',
    deptFilter: 'All',
    statusFilter: 'All',
    sortField: 'firstName',
    sortOrder: 'asc',
  },
  status: 'idle',
  error: null,
});

const employeeSlice = createSlice({
  name: 'employees',
  initialState,
  reducers: {
    setSearchTerm: (state, action) => {
      state.filters.searchTerm = action.payload;
    },
    setFilters: (state, action) => {
      state.filters = { ...state.filters, ...action.payload };
    },
  },
  extraReducers: (builder) => {
    builder
      .addCase(fetchEmployees.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(fetchEmployees.fulfilled, (state, action) => {
        state.status = 'succeeded';
        employeesAdapter.setAll(state, action.payload);
      })
      .addCase(fetchEmployees.rejected, (state, action) => {
        state.status = 'failed';
        state.error = action.payload;
      })
      .addCase(addEmployee.fulfilled, employeesAdapter.addOne)
      .addCase(updateEmployee.fulfilled, (state, action) => {
        // The adapter's updateOne reducer expects an object with { id, changes }
        employeesAdapter.updateOne(state, { id: action.payload.id, changes: action.payload });
      })
      .addCase(deleteEmployee.fulfilled, employeesAdapter.removeOne);
  }
});

export const { setSearchTerm, setFilters } = employeeSlice.actions;

export default employeeSlice.reducer;

// Export the memoized selectors generated by the adapter
export const {
  selectAll: selectAllEmployees,
  selectById: selectEmployeeById,
  selectIds: selectEmployeeIds,
} = employeesAdapter.getSelectors((state) => state.employees);

export const selectEmployeeFilters = (state) => state.employees.filters;

// Memoized selector to get filtered and sorted employees
export const selectVisibleEmployees = createSelector(
  [selectAllEmployees, selectEmployeeFilters],
  (employees, filters) => {
    const { searchTerm, deptFilter, statusFilter, sortField, sortOrder } = filters;
    const filtered = employees?.filter((employee) => {
      const fullName = `${employee?.firstName ?? ''} ${employee?.lastName ?? ''}`.toLowerCase();
      return (
        fullName.includes(searchTerm.toLowerCase()) &&
        (deptFilter === 'All' || employee?.department === deptFilter) &&
        (statusFilter === 'All' || employee?.status === statusFilter)
      );
    });

    return filtered.sort((a, b) => {
      const direction = sortOrder === 'asc' ? 1 : -1;
      const aValue = a[sortField] ?? '';
      const bValue = b[sortField] ?? '';
      return aValue > bValue ? direction : aValue < bValue ? -direction : 0;
    });
  }
);