import { createSlice, createEntityAdapter, createSelector, createAsyncThunk } from '@reduxjs/toolkit';
import { api } from '../../utils/api';

const API_BASE_URL = 'http://localhost:5000/api';

// Async thunk for fetching all employees
export const fetchEmployees = createAsyncThunk(
  'employees/fetchEmployees',
  async (_, { rejectWithValue }) => {
    try {
      const response = await api(`${API_BASE_URL}/employees`);
      return await response.json();
    } catch (error) {
      return rejectWithValue(error.message);
    }
  }
);

// Async thunk for adding an employee
export const addEmployee = createAsyncThunk(
  'employees/addEmployee',
  async (employeeData, { rejectWithValue }) => {
    try {
      const response = await api(`${API_BASE_URL}/employees`, {
        method: 'POST',
        body: JSON.stringify(employeeData),
      });
      return await response.json();
    } catch (error) {
      return rejectWithValue(error.message);
    }
  }
);

// Async thunk for updating an employee
export const updateEmployee = createAsyncThunk(
  'employees/updateEmployee',
  async ({ id, changes }, { rejectWithValue }) => {
    try {
      const response = await api(`${API_BASE_URL}/employees/${id}`, {
        method: 'PATCH',
        body: JSON.stringify(changes),
      });
      return await response.json();
    } catch (error) {
      return rejectWithValue(error.message);
    }
  }
);

// Async thunk for deleting an employee
export const deleteEmployee = createAsyncThunk(
  'employees/deleteEmployee',
  async (employeeId, { rejectWithValue }) => {
    try {
      await api(`${API_BASE_URL}/employees/${employeeId}`, {
        method: 'DELETE',
      });
      // On success, we return the ID so the reducer knows which employee to remove
      return employeeId;
    } catch (error) {
      return rejectWithValue(error.message);
    }
  }
);

// Create an entity adapter for employees.
// The `selectId` function tells the adapter that the unique ID for each employee is `employee.id`.
// The `sortComparer` function keeps the employee array sorted by first name, which can be useful for display.
const employeesAdapter = createEntityAdapter({
  selectId: (employee) => employee.id,
  sortComparer: (a, b) => a.firstName.localeCompare(b.firstName),
});

// Get the initial state from the adapter and populate it with seed data.
// The adapter creates an `{ ids: [], entities: {} }` structure.
const initialState = employeesAdapter.getInitialState({
  filters: {
    searchTerm: '',
    deptFilter: 'All',
    statusFilter: 'All',
    sortField: 'firstName',
    sortOrder: 'asc',
  },
  status: 'idle',
  error: null,
});

const employeeSlice = createSlice({
  name: 'employees',
  initialState,
  reducers: {
    setSearchTerm: (state, action) => {
      state.filters.searchTerm = action.payload;
    },
    setFilters: (state, action) => {
      state.filters = { ...state.filters, ...action.payload };
    },
  },
  extraReducers: (builder) => {
    builder
      .addCase(fetchEmployees.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(fetchEmployees.fulfilled, (state, action) => {
        state.status = 'succeeded';
        employeesAdapter.setAll(state, action.payload);
      })
      .addCase(fetchEmployees.rejected, (state, action) => {
        state.status = 'failed';
        state.error = action.payload;
      })
      .addCase(addEmployee.fulfilled, employeesAdapter.addOne)
      .addCase(updateEmployee.fulfilled, (state, action) => {
        // The adapter's updateOne reducer expects an object with { id, changes }
        employeesAdapter.updateOne(state, { id: action.payload.id, changes: action.payload });
      })
      .addCase(deleteEmployee.fulfilled, employeesAdapter.removeOne);
  }
});

export const { setSearchTerm, setFilters } = employeeSlice.actions;

export default employeeSlice.reducer;

// Export the memoized selectors generated by the adapter
export const {
  selectAll: selectAllEmployees,
  selectById: selectEmployeeById,
  selectEntities: selectEmployeeEntities,
  selectIds: selectEmployeeIds,
} = employeesAdapter.getSelectors((state) => state.employees);

export const selectEmployeeFilters = (state) => state.employees.filters;

// Memoized selector to get filtered and sorted employees
export const selectVisibleEmployees = createSelector(
  [selectAllEmployees, selectEmployeeFilters],
  (employees, filters) => {
    const { searchTerm, deptFilter, statusFilter, sortField, sortOrder } = filters;
    const filtered = employees?.filter((employee) => {
      const fullName = `${employee?.firstName ?? ''} ${employee?.lastName ?? ''}`.toLowerCase();
      return (
        fullName.includes(searchTerm.toLowerCase()) &&
        (deptFilter === 'All' || employee?.department === deptFilter) &&
        (statusFilter === 'All' || employee?.status === statusFilter)
      );
    });

    return filtered.sort((a, b) => {
      const direction = sortOrder === 'asc' ? 1 : -1;
      const aValue = a[sortField] ?? '';
      const bValue = b[sortField] ?? '';
      return aValue > bValue ? direction : aValue < bValue ? -direction : 0;
    });
  }
);

// Memoized selector to get the current user's team
export const selectMyTeam = createSelector(
  [selectAllEmployees, (state) => state.auth.user], // Depends on all employees and the current user session
  (employees, session) => {
    if (!session || !employees) {
      return [];
    }

    const myDepartment = session.department;

    // Find the manager of the user's department
    const departmentManager = employees.find(
      (emp) => emp.department === myDepartment && emp.isDepartmentManager
    );

    // Find all employees in the department
    const departmentMembers = employees.filter(
      (emp) => emp.department === myDepartment
    );

    // If the current user is the manager, they are already included.
    // If not, we need to make sure they are included if they are viewing their own team.
    // The simplest way is to just return all members of the department.
    // The manager will be one of them, and the user will see themselves.
    // We can then sort to ensure the manager is always first.

    // Return the manager first, followed by the rest of the team
    return departmentMembers.sort((a, b) => {
      if (a.isDepartmentManager) return -1;
      if (b.isDepartmentManager) return 1;
      return a.firstName.localeCompare(b.firstName);
    });
  }
);

// Memoized selector to get the current user's team, filtered and sorted
export const selectMyTeamFilteredAndSorted = createSelector(
  [selectMyTeam, selectEmployeeFilters],
  (myTeam, filters) => {
    const { searchTerm, sortField, sortOrder } = filters;

    const filtered = myTeam?.filter((employee) => {
      const fullName = `${employee?.firstName ?? ''} ${employee?.lastName ?? ''}`.toLowerCase();
      return fullName.includes(searchTerm.toLowerCase());
    });

    return filtered.sort((a, b) => {
      const direction = sortOrder === 'asc' ? 1 : -1;
      const aValue = a[sortField] ?? '';
      const bValue = b[sortField] ?? '';
      return aValue > bValue ? direction : aValue < bValue ? -direction : 0;
    });
  }
);