import { createSlice, createEntityAdapter, createSelector } from '@reduxjs/toolkit';
import { employeeSeedData } from '../../data';

// Create an entity adapter for employees.
// The `selectId` function tells the adapter that the unique ID for each employee is `employee.id`.
// The `sortComparer` function keeps the employee array sorted by first name, which can be useful for display.
const employeesAdapter = createEntityAdapter({
  selectId: (employee) => employee.id,
  sortComparer: (a, b) => a.firstName.localeCompare(b.firstName),
});

// Get the initial state from the adapter and populate it with seed data.
// The adapter creates an `{ ids: [], entities: {} }` structure.
const initialState = employeesAdapter.getInitialState({
  filters: {
    searchTerm: '',
    deptFilter: 'All',
    statusFilter: 'All',
    sortField: 'firstName',
    sortOrder: 'asc',
  },
});

const employeeSlice = createSlice({
  name: 'employees',
  initialState,
  reducers: {
    // Use the adapter's `addOne` reducer to add a new employee
    addEmployee: employeesAdapter.addOne,
    // Use the adapter's `updateOne` reducer to update an existing employee
    updateEmployee: employeesAdapter.updateOne,
    // Use the adapter's `removeOne` reducer to delete an employee
    deleteEmployee: employeesAdapter.removeOne,
    // Use the adapter's `setAll` reducer to replace all employees
    setEmployees: employeesAdapter.setAll,
    // To reset, we can just return the initial state
    resetEmployees: (state) => {
        employeesAdapter.setAll(state, employeeSeedData);
        state.filters = initialState.filters;
    },
    setSearchTerm: (state, action) => {
      state.filters.searchTerm = action.payload;
    },
    setFilters: (state, action) => {
      state.filters = { ...state.filters, ...action.payload };
    },
  },
});

export const {
  addEmployee,
  updateEmployee,
  deleteEmployee,
  setEmployees,
  resetEmployees,
  setSearchTerm,
  setFilters,
} = employeeSlice.actions;

export default employeeSlice.reducer;

// Export the memoized selectors generated by the adapter
export const {
  selectAll: selectAllEmployees,
  selectById: selectEmployeeById,
  selectIds: selectEmployeeIds,
} = employeesAdapter.getSelectors((state) => state.employees);

export const selectEmployeeFilters = (state) => state.employees.filters;

// Memoized selector to get filtered and sorted employees
export const selectVisibleEmployees = createSelector(
  [selectAllEmployees, selectEmployeeFilters],
  (employees, filters) => {
    const { searchTerm, deptFilter, statusFilter, sortField, sortOrder } = filters;
    const filtered = employees.filter((employee) => {
      const fullName = `${employee.firstName} ${employee.lastName}`.toLowerCase();
      return (
        fullName.includes(searchTerm.toLowerCase()) &&
        (deptFilter === 'All' || employee.department === deptFilter) &&
        (statusFilter === 'All' || employee.status === statusFilter)
      );
    });

    return filtered.sort((a, b) => {
      const direction = sortOrder === 'asc' ? 1 : -1;
      const aValue = a[sortField] ?? '';
      const bValue = b[sortField] ?? '';
      return aValue > bValue ? direction : aValue < bValue ? -direction : 0;
    });
  }
);